Update go.yml

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -10,13 +10,13 @@ on:
     branches: [ "master" ]
 
 jobs:
+
   build:
     runs-on: ubuntu-latest
     permissions:
       checks: write
     steps:
-    - name: Check Out Code
-      uses: actions/checkout@v4
+    - uses: actions/checkout@v4
 
     - name: Set up Go
       uses: actions/setup-go@v4
@@ -29,32 +29,29 @@ jobs:
         path: |
           ~/.cache/go-build
           ~/go/pkg/mod
-        key: go-mod-${{ runner.os }}-${{ hashFiles('**/go.sum') }}-${{ hashFiles('go.mod') }}
+        key: go-mod-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
         restore-keys: |
           go-mod-${{ runner.os }}-
 
-    - name: Install Dependencies
-      run: go mod download
+    - name: Revive Action
+      uses: morphy2k/revive-action@v2.4.1
 
-    - name: Install Staticcheck
-      run: go install honnef.co/go/tools/cmd/staticcheck@v0.5.2
+    - name: Staticcheck
+      uses: dominikh/staticcheck-action@v1
 
-    - name: Run Staticcheck
-      run: staticcheck ./...
-      env:
-        STATICCHECK_CACHE: "/home/runner/work/_temp/staticcheck" # Explicit cache path
-
-    - name: Build Project
-      run: go build -v ./...
-
-    - name: Run Tests with gotestsum
+    - name: Build
       run: |
+        go build -v ./...
+        go mod download
         go install gotest.tools/gotestsum@latest
+ 
+    - name: Test
+      run: |
         gotestsum --format=standard-verbose --junitfile=junit.xml
 
     - name: Publish Test Report
       uses: mikepenz/action-junit-report@v3
-      if: always()
+      if: success() || failure() # always run even if the previous step fails
       with:
         report_paths: '**/junit.xml'
         detailed_summary: true
